name: Testing on Windows, macOS and Linux

on
  push:
    branches:
      - master
jobs:
  tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.x"

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./client
  tests-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.x"

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./client
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.x"

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./client
